#!/bin/bash -e

if [[ -z "$1" ]]
then
  echo "Usage: recrypt PATH"
  exit
fi

decrypt "$1"

read -p "Press enter to continue..."

dir="$(dirname "$1")"
base="$(basename "$(basename "$1" .gpg)" .zip)"

encrypt "$dir/$base"
